### ISSUE TITLE
Manage nailgun branches to run across different versions

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/satellite-populate#11]
We need to run populate across different versions and nailgun has one branch/tag for each sat version.

initial idea is using

```pip install satellite-populate[6.2]```

and then defining that `[6.2]` we are telling that nailgun requirement is that specific version.

but we have some issues to solve:

- Nailgun should be released to PyPI 
  (we can do automatically for every version bump in master branch, but we should have better version management in nailgun)
- maybe we need Populator class for specific version, if RAW_SEARCH_RULES changed across branches.

**Comment by rochacbruno** [comment]
@JacobCallahan has the solution, we create docker images for each version and each image grabs nailgun from github using specific tag.

**Comment by JacobCallahan** [comment]
this can be managed, per-branch, in that branch's Dockerfile.

alternatively, if you don't want to have separate branches of satellite-populate, then we would have to create a new repo with just the dockerfile

**Comment by rochacbruno** [comment]
@JacobCallahan cant we have a folder `.dockerfiles/` and put everything in there? So dockerhub builds from subfolder and each subfolder is tagged with satellite version.

**Comment by JacobCallahan** [comment]
Ideally, we would drop the Dockerfile in the base directory of this project. Then we can manage the tags by git branches or git tags (just learned the later).

**Comment by rochacbruno** [comment]
@JacobCallahan  Lets use
**tag 6.1**
```
/.dockerfiles/6.1/Dockerfile   
```
Using this requirements.txt

```
# Uses nailgun from PyPI 
nailgun

# Install populate itself to the path
--editable .
```
-----
**tag 6.2**
```
/.dockerfiles/6.2/Dockerfile 
``` 

Using this requirements.txt

```
# Install nailgun specific branch
git+https://github.com/SatelliteQE/nailgun.git@6.2.z#egg=nailgun

# Install populate itself to the path
--editable .
```

------
**tag latest**

```
/.dockerfiles/6.3/Dockerfile  
``` 


Using requirements.txt from root folder
