### ISSUE TITLE
satellite-populate properties file

### ISSUE THREAD

**Issue by chbrown13** [SatelliteQE/satellite-populate#63]
A config file to store properties and avoid always copying arguments such as -h <hostname> and other configuration data. Similar to robotello.properties (https://github.com/SatelliteQE/robottelo/blob/master/robottelo.properties.sample)

**Comment by rochacbruno** [comment]
nice, we can read a `SATELLITE_POPULATE_FILE` environment variable with the path to the file, if not found defaults to `~/.satellitepopulate`

**Comment by chbrown13** [comment]
Link with #71, possible option to config file

**Comment by chbrown13** [comment]
Fixed in PR #86
