### ISSUE TITLE
Clean up validation files

### ISSUE THREAD

**Issue by chbrown13** [SatelliteQE/satellite-populate#71]
When running satellite-populate, validation files are created and stored. If a user runs the program many times then the directory will become cluttered with a lot of validation .yaml files. Perhaps there's a way to delete them after a satellite-populate command finishes running.

**Comment by rochacbruno** [comment]
@chbrown13  You can pass `--no-output` to the command

**Comment by rochacbruno** [comment]
https://github.com/SatelliteQE/satellite-populate/blob/master/satellite_populate/commands.py#L141

**Comment by chbrown13** [comment]
Ok thanks

**Comment by rochacbruno** [comment]
@chbrown13 yeah this option could be persisted in `~/.satellitepopulaterc` onde we implement this

**Comment by chbrown13** [comment]
Ok, makes sense

**Comment by chbrown13** [comment]
Link with #63, possible option to config file
